name: Fb2.Document CI

on:
  push:
  pull_request:
    paths-ignore:
      - "**/**.md"

# side-by-side build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build library
        run: dotnet build -c release

      - name: Run tests
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
        with:
          reports: "**/TestResults/**/*.xml" # REQUIRED # The coverage reports that should be parsed (separated by semicolon). Globbing is supported.
          targetdir: "coveragereport" # REQUIRED # The directory where the generated report should be saved.
          reporttypes: "HtmlSummary" # The output formats and scope (separated by semicolon) Values: Badges, Clover, Cobertura, CsvSummary, Html, HtmlChart, HtmlInline, HtmlInline_AzurePipelines, HtmlInline_AzurePipelines_Dark, HtmlSummary, JsonSummary, Latex, LatexSummary, lcov, MarkdownSummary, MHtml, PngChart, SonarQube, TeamCitySummary, TextSummary, Xml, XmlSummary
          verbosity: "Info" # The verbosity level of the log messages. Values: Verbose, Info, Warning, Error, Off
          toolpath: "reportgeneratortool" # Default directory for installing the dotnet tool.

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.os }}-coverageReport # Artifact name
          path: coveragereport # Directory containing files to upload
