env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

name: Fb2.Document CI

on:
  push:
    paths-ignore:
      - "**/**.md"
  pull_request:
  workflow_dispatch:

# side-by-side build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 3.1.x / 5.0.x / 6.0.x / 7.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            3.1.x
            5.0.x
            6.0.x
            7.0.x

      - name: Build library
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"

      - name: NuGet pack
        run: dotnet pack 'Fb2.Document/Fb2.Document.csproj' --configuration Release --no-build --output dist

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.os }}-nuget
          path: dist

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
        with:
          reports: "**/TestResults/**/*.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlSummary"
          verbosity: "Info"
          toolpath: "reportgeneratortool"

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.os }}-coverageReport
          path: coveragereport
