name: Fb2.Document CI

on:
  push:
    branches:
      - "features/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build library
        run: dotnet build --no-restore --configuration release
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
