name: .NET

on:
  push:
    branches:
      - "features/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build library
        run: dotnet build "Fb2.Document\Fb2.Document.csproj" --no-restore --configuration release
      - name: Tests
        run: dotnet test "Fb2.Document.Tests\Fb2.Document.Tests.csproj" --verbosity normal
